# Generated by Django 4.2.4 on 2023-08-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_cart_cartitem_cartid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='productId',
            new_name='product',
        ),
    ]
